sudo: required
language: python
cache: pip

services:
  - docker

python:
- 3.6.6
install:
- pip install pipenv
- pipenv install --system --ignore-pipfile
- pipenv install awscli --system --ignore-pipfile
- sudo apt-get -y install jq
- curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
- sudo chmod +x /usr/bin/ecs-deploy
sciprt:
- python app/manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_3a3073cf4f6a_key -iv $encrypted_3a3073cf4f6a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
after_success:
- bash .bin/ecr_credentials.sh
- bash .bin/docker_push.sh
- bash .bin/ecs_deploy.sh