sudo: required
language: python
python:
- 3.6.6
install:
- pip install pipenv
- pip install --system --ignore-pipfile
sciprt:
- python app/manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_3a3073cf4f6a_key -iv $encrypted_3a3073cf4f6a_iv
  -in secrets.tar.enc -out secrets.tar -d
