sudo: required

services:
  - docker

language: python
python:
  - 3.6.6

before_install:
  - openssl aes-256-cbc -K $encrypted_3a3073cf4f6a_key -iv $encrypted_3a3073cf4f6a_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar

install:
  - pip install pipenv
  - pipenv install --dev --system --ignore-pipfile
  - sudo apt-get install jq
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy

script:
  - app/pytest --cov=./

after_success:
  - codecov -t $CODECOV_TOEKEN
  - bash .bin/ecr_credentials.sh
  - bash .bin/docker_push.sh
  - bash .bin/ecs_deploy.sh